config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }


  root 'welcome#index'


  get 'welcome/index'

  get 'welcome/about'

  get 'welcome/shop'

  resources :polls

end

app/models/poll.rb
class Poll < ApplicationRecord
  belongs_to :user

  enum vote: [:approve, :disapprove, :novote]

  before_save { self.vote ||= :novote }

end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :authorize_user, except: [:new, :create]

  def new
    @poll = Poll.new
  end

  def create
    @poll = Poll.new(poll_params)
    @poll.user = current_user


    if @poll.save
      flash[:notice] = "Your vote was saved!"
      redirect_to @poll
    else
      flash.now[:alert] = "There was a problem saving your vote.  Please try again."
      render :new
    end
  end

  def edit
    @poll = Poll.find(params[:id])
  end

  def update
    @poll = Poll.find(params[:id])
    @poll.assign_attributes(poll_params)

    if @poll.save
      flash[:notice] = "Your vote was updated."
      redirect_to @poll
    else
      flash.now[:alert] = "There was an error saving your vote. Please try again."
      render :edit
    end
  end

  def show
    @poll = Poll.find(params[:id])
  end

  private

  def poll_params
    params.permit(:vote)
  end

  def authorize_user
    poll = Poll.find(params[:id])

    unless current_user == poll.user
      flash[:alert] = "Oops.  You can't do that.  Have a look at our home page."
      redirect_to welcome_index_path
    end
  end

end

app/helpers/polls_helper.rb
module PollsHelper
  def vote_count
    all_votes = Poll.group(:vote).count
    votes = Hash.new
    all_votes.each do |key, value|
        key = key.upcase
        votes[key] = (value.to_f / Poll.count) * 100
    end
    votes
  end

  # def votes_by_state
  #   s_votes = Hash.new
  #   state_polls = Hash.new
  #   all_polls = Poll.all
  #   all_polls.each do |key, value|
  #     if key.user.state == current_user.state
  #       state_polls[key] = key[value]
  #     end
  #   end
  #   approve = 0
  #   disapprove = 0
  #   novote = 0
  #   state_polls.each do |k, v|
  #     if k == "approve"
  #       approve += 1
  #     elsif k == "disapprove"
  #       disapprove += 1
  #     elsif k == "novote"
  #       novote += 1
  #     end
  #   end
  #
  #   s_votes = {"approve" => approve, "disapprove" => disapprove, "novote" => novote}
  #   state_polls
  # end


end

app/views/polls/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>
        Update your vote:
      </h1>
      <h2 class="text-muted">
        <% if @poll.vote == "novote" %>
        You neither approve nor disapprove of the president right now.
        <% else %>
        You currently <%= @poll.vote %> of the president.
        <% end %>
      </h2>
    </div>

      <!-- <div class="column is-hidden-mobile has-text-right">
        <div class= "is-overlay">
            <iframe src="//rcm-na.amazon-adsystem.com/e/cm?o=1&p=14&l=ur1&category=gift_certificates&banner=0S32YAVKXXKQGNQSSGG2&f=ifr&linkID=e89303503b4dc489264ac8744a057cff&t=bllite-20&tracking_id=bllite-20" width="160" height="600" scrolling="no" border="0" marginwidth="0" style="border:none;" frameborder="0"></iframe>
        </div>
      </div> -->
    </div>
  </br>
  </br>
    <h3>How do you feel about the job that Donald Trump is doing today?</h3>

  </div> <!-- container -->
  <br>


<div class="container">
      <%= form_for @poll do |f| %>
      <div class="card card-success text-center" style="width: 24rem;">
      </br>
        <label class="radio">
          <%= radio_button_tag(:vote, "approve") %>
        </label>
      </br>
        <span>
          Approve for now
        </span>
        <span>
          <i class="fa fa-thumbs-up fa-4x" aria-hidden="true"></i>
        </span>
      </div>
      </br>
      </br>

      <div class="card card-danger text-center" style="width: 24rem;">
      </br>
        <label class="radio">
          <%= radio_button_tag(:vote, "disapprove") %>
        </label>
      </br>
        <span>
          Disapprove for now
        </span>
        <span>
          <i class="fa fa-thumbs-down fa-4x" aria-hidden="true"></i>
        </span>
      </div>
      </br>
      </br>

      <div class="card card-warning text-center" style="width: 24rem;">
      </br>
        <label class="radio">
          <%= radio_button_tag(:vote, "novote") %>
        </label>
      </br>
        <span>
          I'll sit out for now.
        </span>
        <span>
          <i class="fa fa-hand-paper-o fa-4x" aria-hidden="true"></i>
        </span>
      </div>
      </br>
      </br>

        <%= f.submit "Save Your Vote", class: "btn btn-primary btn-lg" %>

        <% end %>


</br>
</br>

  <div class="container">
    <p>
      Do you wear shirts? Visit our store.
      <i class="fa fa-arrow-right fa-lg" aria-hidden="true"></i>
      <i class="fa fa-arrow-right fa-lg" aria-hidden="true"></i>
      <i class="fa fa-arrow-right fa-lg" aria-hidden="true"></i>
      <i class="fa fa-arrow-right fa-lg" aria-hidden="true"></i>
      <%= link_to "Store", welcome_shop_path, class: 'btn btn-outline-primary' %>
    </p>
  </div>
</br>


      <!-- <div>
        <script src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&adInstanceId=69c55c1b-445e-49e4-897d-9d4ce39c8a35"></script>
      </div> -->

app/views/polls/new.html.erb
<div class="container">
    <div class="row">
      <div class="col">
        <h1>
          Cast your vote!
        </h1>
        <h3 class="text-muted">
          You can change it any time you like.
        </h3>
      </br>
        <h4>
          Do you currently approve or disapprove of how Donald Trump is doing as president of the United States?
        </h4>
      </div>

      <!-- <div class="column is-hidden-mobile has-text-right">
        <div class= "is-overlay">
            <iframe src="//rcm-na.amazon-adsystem.com/e/cm?o=1&p=14&l=ur1&category=gift_certificates&banner=0S32YAVKXXKQGNQSSGG2&f=ifr&linkID=e89303503b4dc489264ac8744a057cff&t=bllite-20&tracking_id=bllite-20" width="160" height="600" scrolling="no" border="0" marginwidth="0" style="border:none;" frameborder="0"></iframe>
        </div>
      </div> -->

    </div>
  </div> <!-- container -->

  <br>


<div class="container">
  <%= form_for @poll do |f| %>
  <div class="card card-success text-center" style="width: 24rem;">
  </br>
    <label class="radio">
    <%= radio_button_tag(:vote, "approve") %>
    </label>
    </br>
    <span>
      Approve for now
    </span>
    <span>
      <i class="fa fa-thumbs-up fa-4x" aria-hidden="true"></i>
    </span>
  </div>
  </br>
  </br>

  <div class="card card-danger text-center" style="width: 24rem;">
  </br>
    <label class="radio">
    <%= radio_button_tag(:vote, "disapprove") %>
    </label>
    </br>
    <span>
      Disapprove for now
    </span>
    <span>
      <i class="fa fa-thumbs-down fa-4x" aria-hidden="true"></i>
    </span>
  </div>
  </br>
  </br>

  <div class="card card-warning text-center" style="width: 24rem;">
  </br>
    <label class="radio">
    <%= radio_button_tag(:vote, "novote") %>
    </label>
    </br>
    <span>
      I'll sit out for now.
    </span>
    <span>
      <i class="fa fa-hand-paper-o fa-4x" aria-hidden="true"></i>
    </span>
  </div>
  </br>
  </br>
      <%= f.submit "Save Your Vote", class: "btn btn-primary btn-large" %>

      <% end %>
</br>
</br>

  <div class="container">
    <div class="row">
      <div class="card card-danger card-inverse text-white" style="width: 24rem;">

          Do you wear shirts? Visit our store after you vote.

      </div>
    </div>

  </div>
</br>

  <!-- <div>
      <div>
        <script src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&adInstanceId=69c55c1b-445e-49e4-897d-9d4ce39c8a35"></script>
      </div>
  </div> -->

app/views/polls/show.html.erb
<!-- Amazon banner -->
<div class="container">

      <!-- <div class="column text-center">
          <p><script src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&adInstanceId=69c55c1b-445e-49e4-897d-9d4ce39c8a35"></script></p>
      </div> -->
      <!-- Current vote -->
  <div class="card card-outline-success" style="width: 24rem;">
    <div class="card-header">
      <h1>Your current vote:<h1>
    </div>
    </br>
    <h2 class="text-center"><%= link_to current_user.poll.vote.upcase, edit_poll_path(current_user.poll), class: "btn btn-success" %></h2>
    <p class="text-center">Click to update your vote</p>
  </div>
</br>
</br>

<div class="card-group">
  <div class="card card-outline-primary" style="width: 24rem;">
    <div class="card-header">
      <h2 class="text-center">Live Results</h2>
    </div>
    <%= area_chart(vote_count) %>
  </div>

</br>
</br>
  <div class="card card-outline-primary" style="width: 24rem;">
    <div class="card-header">
      <h2 class="text-center">Live Results</h2>
    </div>
    <%= pie_chart(vote_count) %>
  </div>
</br>
</br>
  <div class="card card-outline-primary" style="width: 24rem;">
    <div class="card-header">
      <h2 class="text-center">COMING SOON: Results by state</h2>
    </div>
    <%= pie_chart(vote_count) %>
  </div>
</div> <!--card group -->
</div> <!--container -->

</br>


    <!-- Trump's Twitter feed -->
    <div class="container">
      <div class="col">
        <div class="column text-center">
          <a class="twitter-timeline" data-height="300" data-width="820" data-theme="dark" href="https://twitter.com/realDonaldTrump">Tweets by realDonaldTrump</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>
      </div>