config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }


  root 'welcome#index'


  get 'welcome/index'

  get 'welcome/about'

  get 'welcome/shop'

  resources :polls

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="icon" href="/images/trumpmeter_stamp2.jpg">
    <title>Trumpmeter</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= javascript_include_tag 'application', 'Chart.bundle', 'chartkick', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <% if notice %>
        <div class="alert alert-success alert-dismissable">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>


    <nav class="navbar navbar-inverse bg-primary navbar-toggleable-md fixed-top">

      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand btn btn-primary" href="/welcome/index">TrumpMeter</a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

          <li class="nav-item">
            <%= link_to "Shop", welcome_shop_path, class: 'nav-link btn btn-primary' %>
          </li>

          <li class="nav-item">
            <% if current_user && (current_user.poll != nil) %>
            <%= link_to "Poll", poll_path(current_user.poll), class: 'nav-link btn btn-primary' %>
            <% else %>
            <%= link_to "Poll", new_poll_path, class: 'nav-link btn btn-primary' %>
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to "About", welcome_about_path, class: 'nav-link btn btn-primary' %>
          </li>


          <% if user_signed_in? %>
          <li class="nav-item">
              <%= link_to ("<i class='fa fa-user'></i> Edit Profile").html_safe, edit_user_registration_path, :class => 'nav-link btn btn-primary' %>
          </li>
          <li class="nav-item">
            <%= link_to ("<i class='fa fa-sign-out'></i> Sign Out").html_safe, destroy_user_session_path, method: :delete, :class => "nav-link btn btn-primary" %>
          </li>
            <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, :class => 'nav-link btn btn-primary' %>
          </li>
          <li class="nav-item">
            <%= link_to ("<i class='fa fa-sign-in'></i> Sign In").html_safe, new_user_session_path, :class => 'nav-link btn btn-primary' %>
            <% end %>
          </li>

          </ul>
        </div>
      </div>
    </nav>
  </br>


    <%= yield %>

  <footer class="footer">
    <div class="container text-center">
      <span class="text-muted">
          <%= link_to "Home", welcome_index_path %>
          <%= link_to "About", welcome_about_path %>
          <%= link_to "Shop", welcome_shop_path %>
          &copy; 2017 TrumpMeter.co
      </span>
    </div>
  </footer>

  </body>
</html>